{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "10f7d5fc-3b98-43c6-aee6-e1b7113c829e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)\n",
    "os.environ['CUDA_ENABLE_DEVICES'] = \"1\"\n",
    "import pathlib\n",
    "import tensorflow as tf\n",
    "\n",
    "import time\n",
    "from object_detection.utils import label_map_util\n",
    "from object_detection.utils import config_util\n",
    "from object_detection.utils import visualization_utils as viz_utils\n",
    "from object_detection.builders import model_builder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f516bdb1-535f-4d37-a130-cd25178f9eb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "PATH_TO_MODEL_DIR = \"/home/dammeier@ab.ba.ba-ravensburg.de/dev/oil-storage-detection/data/06_models/models/efficientdet_d4\"\n",
    "PATH_TO_CONFIG = PATH_TO_MODEL_DIR + \"/pipeline.config\"\n",
    "PATH_TO_CHECKPOINT = PATH_TO_MODEL_DIR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4f4df57c-1493-4ac1-aa26-1ca53053a900",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading model... Done! Took 18.651562690734863 seconds\n"
     ]
    }
   ],
   "source": [
    "print('Loading model... ', end='')\n",
    "start_time = time.time()\n",
    "\n",
    "# Load pipeline confic and build a detection model\n",
    "configs = config_util.get_configs_from_pipeline_file(PATH_TO_CONFIG)\n",
    "model_config = configs['model']\n",
    "detection_model = model_builder.build(model_config=model_config, is_training=False)\n",
    "\n",
    "# Restore checkpoint\n",
    "checkpoint = tf.compat.v2.train.Checkpoint(model=detection_model)\n",
    "checkpoint.restore(os.path.join(PATH_TO_CHECKPOINT, 'ckpt-32')).expect_partial()\n",
    "\n",
    "@tf.function\n",
    "def detect_fn(image):\n",
    "    \"\"\"Detect objects in image.\"\"\"\n",
    "    image, shapes = detection_model.preprocess(image)\n",
    "    prediction_dict = detection_model.predict(image, shapes)\n",
    "    detections = detection_model.postprocess(prediction_dict, shapes)\n",
    "    \n",
    "    return detections\n",
    "\n",
    "end_time = time.time()\n",
    "elapsed_time = end_time - start_time\n",
    "print(f'Done! Took {elapsed_time} seconds')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "85e0243a-7008-415a-aaad-8db869e4d87f",
   "metadata": {},
   "outputs": [],
   "source": [
    "category_index = {1: 'OST'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "c236a007-3511-4061-b87e-94770cae83d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore') # suppress mpl warnings\n",
    "\n",
    "def load_image_to_numpy_array(image_path):\n",
    "    return np.array(Image.open(image_path))\n",
    "\n",
    "def run_inference_on_image(image_path):\n",
    "    print(f'Running inference for {image_path}...')\n",
    "    \n",
    "    image_np = load_image_to_numpy_array(image_path)\n",
    "    \n",
    "    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)\n",
    "    \n",
    "    detections = detect_fn(input_tensor)\n",
    "    \n",
    "    # All outputs are batches tensors.\n",
    "    # Convert to numpy arrays, and take index [0] to remove the batch dimension.\n",
    "    # We're only interested in the first num_detections.\n",
    "    num_detections = int(detections.pop('num_detections'))\n",
    "    detections = {key: value[0, :num_detections].numpy()\n",
    "                  for key, value in detections.items()}\n",
    "    detections['num_detections'] = num_detections\n",
    "\n",
    "    # detection_classes should be ints.\n",
    "    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)\n",
    "\n",
    "    label_id_offset = 1\n",
    "    image_np_with_detections = image_np.copy()\n",
    "\n",
    "    viz_utils.visualize_boxes_and_labels_on_image_array(\n",
    "            image_np_with_detections,\n",
    "            detections['detection_boxes'],\n",
    "            detections['detection_classes']+label_id_offset,\n",
    "            detections['detection_scores'],\n",
    "            category_index,\n",
    "            use_normalized_coordinates=True,\n",
    "            max_boxes_to_draw=200,\n",
    "            min_score_thresh=.30,\n",
    "            agnostic_mode=False)\n",
    "\n",
    "    plt.figure()\n",
    "    plt.imshow(image_np_with_detections)\n",
    "    print('Done')\n",
    "    plt.show()\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04d9657e-fb39-4f93-a02a-750ad5ef5041",
   "metadata": {},
   "outputs": [],
   "source": [
    "run_inference_on_image('/home/dammeier@ab.ba.ba-ravensburg.de/dev/oil-storage-detection/data/02_intermediate/images/test/4fe78c6c-8c59-4f98-9083-f8117dc19ae0.jpg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "458081b0-6e1d-4632-8a7d-30b79fb5613b",
   "metadata": {},
   "outputs": [],
   "source": [
    "image_np = load_image_to_numpy_array('/home/dammeier@ab.ba.ba-ravensburg.de/dev/oil-storage-detection/data/02_intermediate/images/test/4fe78c6c-8c59-4f98-9083-f8117dc19ae0.jpg')\n",
    "    \n",
    "input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f346f636-b548-44e3-976e-2ccb58aecb48",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-05-24 15:29:58.799706: E tensorflow/stream_executor/cuda/cuda_blas.cc:232] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED\n",
      "2022-05-24 15:29:58.800090: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : NOT_FOUND: No algorithm worked!  Error messages:\n",
      "  Profiling failure on CUDNN engine 1#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 0#TC: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 2#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 5#TC: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
      "  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\n",
      "in tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'EfficientDet-D4/model_1/stem_conv2d/Conv2D' defined at (most recent call last):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/traitlets/config/application.py\", line 972, in launch_instance\n      app.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_1152647/214064768.py\", line 1, in <cell line: 1>\n      detections = detect_fn(input_tensor)\n    File \"/tmp/ipykernel_1152647/512796452.py\", line 17, in detect_fn\n      prediction_dict = detection_model.predict(image, shapes)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 569, in predict\n      if self._feature_extractor.is_keras_model:\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 570, in predict\n      feature_maps = self._feature_extractor(preprocessed_inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 251, in call\n      return self._extract_features(inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py\", line 228, in _extract_features\n      base_feature_maps = self._efficientnet(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n      return tf.nn.convolution(\nNode: 'EfficientDet-D4/model_1/stem_conv2d/Conv2D'\nDetected at node 'EfficientDet-D4/model_1/stem_conv2d/Conv2D' defined at (most recent call last):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/traitlets/config/application.py\", line 972, in launch_instance\n      app.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_1152647/214064768.py\", line 1, in <cell line: 1>\n      detections = detect_fn(input_tensor)\n    File \"/tmp/ipykernel_1152647/512796452.py\", line 17, in detect_fn\n      prediction_dict = detection_model.predict(image, shapes)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 569, in predict\n      if self._feature_extractor.is_keras_model:\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 570, in predict\n      feature_maps = self._feature_extractor(preprocessed_inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 251, in call\n      return self._extract_features(inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py\", line 228, in _extract_features\n      base_feature_maps = self._efficientnet(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n      return tf.nn.convolution(\nNode: 'EfficientDet-D4/model_1/stem_conv2d/Conv2D'\n2 root error(s) found.\n  (0) NOT_FOUND:  No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0#TC: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5#TC: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n\t [[{{node EfficientDet-D4/model_1/stem_conv2d/Conv2D}}]]\n\t [[Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Reshape/_6]]\n  (1) NOT_FOUND:  No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0#TC: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5#TC: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n\t [[{{node EfficientDet-D4/model_1/stem_conv2d/Conv2D}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_detect_fn_61255]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32m/home/dammeier@ab.ba.ba-ravensburg.de/dev/oil-storage-detection/notebooks/02-frederik-dammeier-visualization.ipynb Cell 8'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> <a href='vscode-notebook-cell://ssh-remote%2Bdhbw-bizon/home/dammeier%40ab.ba.ba-ravensburg.de/dev/oil-storage-detection/notebooks/02-frederik-dammeier-visualization.ipynb#ch0000007vscode-remote?line=0'>1</a>\u001b[0m detections \u001b[39m=\u001b[39m detect_fn(input_tensor)\n",
      "File \u001b[0;32m~/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py:153\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py?line=150'>151</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py?line=151'>152</a>\u001b[0m   filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m--> <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py?line=152'>153</a>\u001b[0m   \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[1;32m    <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py?line=153'>154</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py?line=154'>155</a>\u001b[0m   \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=51'>52</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=52'>53</a>\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[0;32m---> <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=53'>54</a>\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=54'>55</a>\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=55'>56</a>\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m     <a href='file:///home/dammeier%40ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tensorflow/python/eager/execute.py?line=56'>57</a>\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'EfficientDet-D4/model_1/stem_conv2d/Conv2D' defined at (most recent call last):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/traitlets/config/application.py\", line 972, in launch_instance\n      app.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_1152647/214064768.py\", line 1, in <cell line: 1>\n      detections = detect_fn(input_tensor)\n    File \"/tmp/ipykernel_1152647/512796452.py\", line 17, in detect_fn\n      prediction_dict = detection_model.predict(image, shapes)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 569, in predict\n      if self._feature_extractor.is_keras_model:\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 570, in predict\n      feature_maps = self._feature_extractor(preprocessed_inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 251, in call\n      return self._extract_features(inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py\", line 228, in _extract_features\n      base_feature_maps = self._efficientnet(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n      return tf.nn.convolution(\nNode: 'EfficientDet-D4/model_1/stem_conv2d/Conv2D'\nDetected at node 'EfficientDet-D4/model_1/stem_conv2d/Conv2D' defined at (most recent call last):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/traitlets/config/application.py\", line 972, in launch_instance\n      app.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_1152647/214064768.py\", line 1, in <cell line: 1>\n      detections = detect_fn(input_tensor)\n    File \"/tmp/ipykernel_1152647/512796452.py\", line 17, in detect_fn\n      prediction_dict = detection_model.predict(image, shapes)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 569, in predict\n      if self._feature_extractor.is_keras_model:\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 570, in predict\n      feature_maps = self._feature_extractor(preprocessed_inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py\", line 251, in call\n      return self._extract_features(inputs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py\", line 228, in _extract_features\n      base_feature_maps = self._efficientnet(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"/home/dammeier@ab.ba.ba-ravensburg.de/miniconda3/envs/tensorflow-osd/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n      return tf.nn.convolution(\nNode: 'EfficientDet-D4/model_1/stem_conv2d/Conv2D'\n2 root error(s) found.\n  (0) NOT_FOUND:  No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0#TC: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5#TC: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n\t [[{{node EfficientDet-D4/model_1/stem_conv2d/Conv2D}}]]\n\t [[Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Reshape/_6]]\n  (1) NOT_FOUND:  No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0#TC: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2#TC: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5#TC: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n\t [[{{node EfficientDet-D4/model_1/stem_conv2d/Conv2D}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_detect_fn_61255]"
     ]
    }
   ],
   "source": [
    "detections = detect_fn(input_tensor)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d140b100-0397-42ef-bdd9-b97896f24b92",
   "metadata": {},
   "outputs": [],
   "source": [
    "detections"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16b44832-643b-4f59-8a84-bab18db698e8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "9763b797e91abcff88b30fb0158ca9b9621827488e019d1a51bbfc7ee01b7128"
  },
  "kernelspec": {
   "display_name": "Python 3.8.13 ('tensorflow-osd')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
